#! /usr/bin/env bash
export DATA=${DATA:-${DATAROOT}/${RUN}fetch_${cyc}}
source "${HOMEgfs}/ush/jjob_header.sh" -e "fetch" -c "base fetch"

# Execute fetching
# Do not export shell opts to the bash scripts in the htar/hsi wrappers
export -n SHELLOPTS
"${SCRgfs}/exglobal_fetch.py"
err=$?

###############################################################
# Check for errors and exit if any of the above failed
if [[ ${err} -ne 0 ]]; then
    err_exit "Unable to fetch ICs to ${ROTDIR}; ABORT!"
fi

if [[ "${DOENKFONLY_ATM_GSI_NCDIAG}" == "YES" ]] ; then
    export FETCH_YAML_TMPL="${PARMgfs}/fetch/${NET}_${APP}_gdas-anl-gsi-ncdiag.yaml.j2"
# Execute fetching
# Do not export shell opts to the bash scripts in the htar/hsi wrappers
export -n SHELLOPTS
"${SCRgfs}/exglobal_fetch.py"
err=$?

###############################################################
# Check for errors and exit if any of the above failed
if [[ ${err} -ne 0 ]]; then
    err_exit "Unable to fetch GSI_NCDIAG to ${ROTDIR}; ABORT!"
else
    cd ${DATA}
    mkdir gsi-ncdiag
    for file in $(ls ./enkfgdas.20220103/18/atmos/*stat.ensmean); do
	tar -xvf "${file}" -C "./gsi-ncdiag"
	err=$?
	if [[ ${err} -ne 0 ]]; then
	    err_exit "Failed to untar ${file}"
	fi
    done
fi
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || exit 1
if [[ "${KEEPDATA}" == "NO" ]]; then
    rm -rf "${DATA}"
fi

exit 0
